### ISSUE TITLE
documentation link is broke

### ISSUE THREAD

**Issue by isbincApps** [DeFUCC/gun-vue#29]
amazing job, where can i find the documentation

**Comment by davay42** [comment]
The docs are here for now https://gun-vue.js.org/components/#/. Should be working. Yet there are going to be some updates on composables docs after full typescript conversion. We'll be changing JSDoc to TypeDoc soon.

**Comment by isbincApps** [comment]
i'm using quasar framework and it doesnt work 

Cannot access 'Mf' before initialization

```
import { boot } from 'quasar/wrappers'

import '@gun-vue/components/dist/style.css'
import { GunVuePlugin } from '@gun-vue/components'


export default boot(({ app }) => {
  app.use(GunVuePlugin)
})

```

**Comment by isbincApps** [comment]
```
[Quasar] boot error: ReferenceError: Cannot access 'Lv' before initialization
    at eval (index-d0444954.js?92af:4012:1)
    at ./node_modules/@gun-vue/components/dist/index-d0444954.js (vendor.js:3055:1)
    at __webpack_require__ (app.js:213:33)
    at fn (app.js:475:21)
    at eval (components.js:245:76)
    at ./node_modules/@gun-vue/components/dist/components.js (vendor.js:3044:1)
    at __webpack_require__ (app.js:213:33)
    at fn (app.js:475:21)
    at eval (gun.js:7:77)
    at ./src/boot/gun.js (app.js:79:1)

```

**Comment by davay42** [comment]
Hmm, the script may be starting in a SSR environment. This behavior is not stable yet. A reactive p2p database is oriented client-side. Try using async components. Or create ones yourself with `@gun-vue/composables`.
