### ISSUE TITLE
Remixed Glitch project, port not working

### ISSUE THREAD

**Issue by Jammooly1** [DeFUCC/gun-vue#7]
I remixed your glitch project and tried to run it so I can have a relay peer, but I keep getting this error. I didn't change anything involving the project.

https://glitch.com/edit/#!/scalloped-enchanting-chameleon?path=README.md%3A1%3A0

```
$ node main.js 
Hello wonderful person! :) Thanks for using GUN, please ask for help on http://chat.gun.eco if anything takes you longer than 5min to figure out!
AXE relay enabled!
Server started at http://etogun.glitch.me:4200
Gun peer link is http://etogun.glitch.me:4200/gun
Data storage is disabled
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::4200
    at Server.setupListenHandle [as _listen2] (node:net:1334:16)
    at listenInCluster (node:net:1382:12)
    at Server.listen (node:net:1469:7)
    at Function.listen (/rbd/pnpm-volume/b505318e-2063-45fe-93e1-3966adf22d1b/node_modules/express/lib/application.js:618:24)
    at Object.init (file:///rbd/pnpm-volume/b505318e-2063-45fe-93e1-3966adf22d1b/node_modules/@gun-vue/relay/server.js:20:22)
    at file:///app/main.js:3:7
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
Emitted 'error' event on WebSocketServer instance at:
    at Server.emit (node:events:390:28)
    at emitErrorNT (node:net:1361:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 4200
}
```

Would you happen to know how to fix this?

**Comment by davay42** [comment]
Hey, you can specify another port with options.port. Try 8080 or any other.
