### ISSUE TITLE
Use composables with Nuxt 3

### ISSUE THREAD

**Issue by Extarys** [DeFUCC/gun-vue#8]
With Nuxt 3, simply importing the composable inside a custom component I get:

```
[vite dev] Error loading external "./node_modules/@gun-vue/composables/dist/vendor.js".

at file://./.nuxt/dist/server/server.mjs:4073:320
at async __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:11220:3)
```

components/gun.vue:
```
<template>
<span v-text="relay"></span>
</template>

<script setup lang="ts">
import { useRelay } from '@gun-vue/composables';

const relay = useRelay();
</script>
```

Is there something else I can do to make this works?

Thanks!

**Comment by davay42** [comment]
I don't have any experience with Nuxt, but seems you can try to set a `build.transpile` option for the package https://v3.nuxtjs.org/concepts/esm/#transpiling-libraries . Please, tell me if it helps.

**Comment by Extarys** [comment]
Thanks for your reply, sadly it doesn't seem to work either:

```
Could not dynamically require "./lib/text-encoding". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.

at commonjsRequire (file://./.nuxt/dist/server/server.mjs:4110:9)
at USE (file://./.nuxt/dist/server/server.mjs:10308:20)
at file://./.nuxt/dist/server/server.mjs:10499:46
at file://./.nuxt/dist/server/server.mjs:10309:9
at file://./.nuxt/dist/server/server.mjs:10517:7
at file://./.nuxt/dist/server/server.mjs:11930:5
at $id_9ae9d2c5 (file://./.nuxt/dist/server/server.mjs:11931:3)
at __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:50127:9)
at __ssrLoadModule__ (file://./.nuxt/dist/server/server.mjs:50074:25)
at ssrImport (file://./.nuxt/dist/server/server.mjs:50099:13)
```


nuxt.config.ts:
```
	build: {
		transpile: ['@gun-vue/composables']
	},
```

I tried with both `@gun-vue/composables` and `@gun-vue`.

I might try to get help from the nuxt discord server and see what happens :/
